### ISSUE TITLE
Build Error - cannot find symbol

### ISSUE THREAD

**Issue by feddischson** [wgoossens/sopc2dts#10]
Hi,

I am getting the following error when running `make` at revsion `5cb43cb`
```
javac Sopc2DTS.java
Sopc2DTS.java:520: error: cannot find symbol
                                        } else if (parameter==extraComponents) {
                                                              ^
  symbol:   variable extraComponents
  location: class Sopc2DTS.CommandLineOption
Sopc2DTS.java:521: error: cannot find symbol
                                                vExtraComponents.add(parameter.value);
                                                ^
  symbol:   variable vExtraComponents
  location: class Sopc2DTS.CommandLineOption
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
2 errors
make: *** [Makefile:122: Sopc2DTS.class] Error 1
```

I am using `javac 1.8.0_181` and it is working with sopc2dts version `rel_14.0_RC3`

**Comment by wgoossens** [comment]
You're absolutely right.
Sorry about that, didn't review the patch good enough.... It is now fixed in current head: 97a55b1d99ff78390661dae61e9e2965f139b578
Thanks for reporting!
Walter
